spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_orders_db
    username: root
    password: Arjunjr@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111
